# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  sequence_diagrams: false
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true
  custom_instructions: |
    # Documentation & AGENTS.md Compliance

    You are the guardian of the project's documentation consistency.

    1. **Check for Architectural Changes**:
       If this PR introduces a new pattern, workflow change, or significant architectural update, check if `AGENTS.md` has been updated to reflect it.
       - If `AGENTS.md` is NOT updated, you MUST provide a specific, committable code suggestion block to update the file. Do not just ask the user to do it.

    2. **Check for Component Skills**:
       If this PR creates or significantly modifies a UI component (under `packages/lynx-ui-*`), check if `SKILL.md` exists and is updated.
       - If `SKILL.md` is missing or outdated, provide the full content of the new/updated `SKILL.md` in a code block so the user can commit it directly.
       - Ensure the "Prompt Formula" section is included.

    3. **Naming Conventions**:
       Ensure the project name is always referred to as **lynx-ui** (lowercase).
       - If you find "Lynx UI" or "Lynx-UI", provide a replacement suggestion immediately.
