// Copyright 2026 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.
// cspell:ignore OTPRTL

const demosByPackage = {
  button: [
    'ButtonBasic',
    'ButtonDisabled',
    'ButtonPropagateTapEvent',
  ],
  checkbox: ['CheckboxBasic', 'CheckboxIndeterminate'],
  common: ['CommonPreCommitHook'],
  deferredComponent: [
    'DeferredComponentBasic',
    'DeferredComponentDelayFrames',
  ],
  dialog: ['DialogBasic', 'DialogBasicTailwind', 'DialogTimingRace'],
  draggable: [
    'DraggableBasic',
    'DraggableWithBounds',
    'DraggableWithArea',
  ],
  feedList: [
    'FeedListBasic',
    'FeedListHorizontal',
    'FeedListHorizontalRTL',
    'FeedListRefresh',
  ],
  form: ['FormBasic', 'FormKeyboardAware'],
  input: [
    'InputBasic',
    'InputKeyboardAwareView',
    'InputKeyboardInScrollView',
  ],
  inputOTP: [
    'InputOTPBasic',
    'InputOTPCapabilities',
    'InputOTPKeyboardAware',
    'InputOTPRTL',
  ],
  lazyComponent: [
    'LazyComponentBasic',
    'LazyComponentVisibilityMargin',
  ],
  list: ['ListBasic', 'ListMaxSize'],
  popover: [
    'PopoverBasic',
    'PopoverBasicTailwind',
    'PopoverOffsetAdjustment',
    'PopoverExtraAnchor',
    'PopoverWithScrollView',
    'PopoverBackdrop',
    'PopoverControlled',
    'PopoverCustomArrow',
  ],
  radioGroup: ['RadioGroupBasic', 'RadioGroupDisabled'],
  scrollCoordinator: [
    'ScrollCoordinatorList',
    'ScrollCoordinatorViewPager',
    'ScrollCoordinatorViewPagerList',
    'ScrollCoordinatorRefreshCoordinator',
    'ScrollCoordinatorRefreshPage',
  ],
  scrollView: [
    'ScrollViewBasic',
    'ScrollViewBounces',
    'ScrollViewBouncesRTL',
    'ScrollViewInnerFlex',
    'ScrollViewNativeUseBounces',
    'ScrollViewScrollBy',
    'ScrollViewZIndex',
  ],
  sheet: [
    'SheetBasic',
    'SheetAutoHeight',
    'SheetControlled',
    'SheetDirectional',
    'SheetImperative',
  ],
  slider: [
    'SliderBasic',
    'SliderControlled',
    'SliderPriceRange',
    'SliderShapes',
    'SliderFacade',
    'SliderDynamicWidth',
    'SliderProgress',
    'SliderWithScrollView',
  ],
  sortable: [
    'SortableBasic',
    'SortableWithScrollView',
    'SortableScrollableBoundary',
    'SortableShortScrollView',
    'SortableNoBoundary',
    'SortableDisableSorting',
    'SortableDisableItems',
  ],
  swipeAction: [
    'SwipeActionBasic',
    'SwipeActionWithScrollView',
  ],
  swiper: [
    'SwiperBasic',
    'SwiperCustomTinder',
    'SwiperDifferentHeight',
    'SwiperBasicDynamic',
    // Debug-only examples are intentionally excluded from the public gallery.
    // 'SwiperEmptyDataBug',
    'SwiperBasicUpdateSize',
    'SwiperWithGap',
    'SwiperBounces',
    'SwiperLoop',
    'SwiperCustom',
    'SwiperCustomScale',
    'SwiperIndicator',
    'SwiperLazy',
    'SwiperRTL',
    'SwiperRTLLoop',
    'SwiperRTLLynxRTL',
    'SwiperRTLCustom',
  ],
  switch: ['SwitchBasic', 'SwitchBasicTailwind', 'SwitchThemed'],
  tabGroup: [
    'TabGroupBasic',
    'TabGroupSizing',
    'TabGroupIndicatorMotion',
    'TabGroupInitialSelection',
    'TabGroupImperativeSelection',
    'TabGroupPanel',
  ],
  viewPager: [
    'ViewPagerBasic',
    'ViewPagerGallery',
    'ViewPagerAutoHeight',
    'ViewPagerDynamicHeight',
    'ViewPagerNestedList',
    'ViewPagerShowcase',
  ],
} as const

export const demos = Object.values(demosByPackage).flat()
